# Generated by Django 3.2 on 2022-10-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0002_blogpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
