# Generated by Django 3.2 on 2022-10-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='date',
            new_name='collection_date',
        ),
    ]
