# Generated by Django 3.2 on 2022-10-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_rename_date_donation_collection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='collection_date',
            field=models.CharField(max_length=100),
        ),
    ]
